const data = [{
        id: 1,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.Lorem ipsum dolor sit amet consectetur adipisicing elit",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 2,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 3,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 4,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 5,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 6,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 7,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 8,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 9,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
    {
        id: 10,
        name: "揭阳市生生模具器有限公司",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, numquam.",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        trackNumber: "UF152445587520",
        deliveryCompany: "EMS express",
        quantity: "123",
        deliveryThroughChina: "25 $",
        itemPrice: "30000 $",
        deliveryPrice: "50 $",
        totalPrice: "60000 $",
    },
]
export default data